name: CI

on:
  pull_request:
    branches:
      - main

jobs:
    job1:
          name: Build
          runs-on: ubuntu-22.04
          container: ros:humble
          steps:
            - name: Install Git
              run: |
                  apt-get update
                  apt-get install -y git
              shell: bash
            - uses: actions/checkout@v2
              with:
                submodules: true
            - name: Copy repository
              run: |
                  mkdir -p ~/ros2_ws/src/imu_estimator
                  cp -rf . ~/ros2_ws/src/imu_estimator
            - name: Install dependencies
              run: |
                  source /opt/ros/humble/setup.bash
                  apt install -y python3-rosdep
                  rosdep update
                  cd ~/ros2_ws/src
                  rosdep install -r -y --from-paths . --ignore-src
              shell: bash
            - name: Build packages
              run: |
                  source /opt/ros/humble/setup.bash
                  apt install -y python3-colcon-common-extensions
                  cd ~/ros2_ws
                  colcon build
                  source ~/ros2_ws/install/setup.bash
              shell: bash

